export * from './authPages/sign-up/sign-up';
export * from './authPages/login/login';
export * from './tabs/tabs'
export * from './tabs/cards/cards'
export * from './tabs/profile/profile'
export * from './admin/cards/admin-cards/admin-cards'
export * from './admin/cards/register-user-to-card/register-user-to-card'
export * from './about/about'
export * from './admin/cards/create-or-update-card/create-or-update-card'
export * from './admin/schools/school-detail/school-detail'
export * from './admin/schools/school-list/school-list'
export * from './admin/users/users-list/users-list'
export * from './admin/users/user-details/user-details'
export * from './all-user-cards/all-user-cards'