export * from './authPages/sign-up/sign-up';
export * from './authPages/login/login';
export * from './tabs/tabs'
export * from './tabs/cards/cards'
export * from './tabs/profile/profile'
export * from './admin/cards/admin-cards/admin-cards'
export * from './admin/cards/register-user-to-card/register-user-to-card'
export * from './about/about'
export * from './admin/cards/create-or-update-card/create-or-update-card'